In [28]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv('salary_data_cleaned.csv')
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,avg_salary,Company_text,job_state,same_state,age,python_yn,R_yn,spark,aws,excel
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,...,72.0,Tecolote Research\n,NM,0,54,1,0,0,0,0
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,...,87.5,University of Maryland Medical System\n,MD,0,43,1,0,0,0,0
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,...,85.0,KnowBe4\n,FL,1,17,1,0,1,0,0
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,76.5,PNNL\n,WA,1,62,1,0,0,0,0
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,...,114.5,Affinity Solutions\n,NY,1,29,1,0,0,0,0

In [30]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'Company_text', 'job_state', 'same_state', 'age', 'python_yn', 'R_yn',
       'spark', 'aws', 'excel'],
      dtype='str')

In [31]:
##job title and seniority
def title_simpifier (title):
    if 'data scientist' in title.lower():
        return 'data scientist'
    elif 'data engineer' in title.lower():
        return 'data engineer'
    elif 'analyst' in title.lower():
        return 'data analyst'
    elif 'machine learning' in title.lower():
        return 'mle'
    elif 'manager' in title.lower():
        return 'manager'
    elif 'director' in title.lower():
        return 'director'
    else: 
        return 'na'
   
def seniority(title):
    if 'sr' in title.lower() or 'senior' in title.lower() or'lead' in title.lower() or 'principal' in title.lower():
           return 'senior'
    elif 'jr' in title.lower() or 'jr.' in title.lower():
           return 'jr'
    else:
        return 'na'

In [32]:
df['job_simp'] = df['Job Title'].apply(title_simpifier)
df.job_simp.value_counts()

job_simp
data scientist    279
na                184
data engineer     119
data analyst      102
manager            22
mle                22
director           14
Name: count, dtype: int64

In [33]:
df['seniority'] = df['Job Title'].apply(seniority)
df.seniority.value_counts()

seniority
na        520
senior    220
jr          2
Name: count, dtype: int64

In [34]:
#fix state las angeles
df['job_state'] = df['job_state'].apply(lambda x: x.replace('Los Angeles', 'CA'))
df.job_state.value_counts()

job_state
CA    152
MA    103
NY     72
VA     41
IL     40
MD     35
PA     33
TX     28
WA     21
NC     21
NJ     17
FL     16
OH     14
TN     13
CO     11
DC     11
IN     10
WI     10
UT     10
MO      9
AZ      9
AL      8
KY      6
MI      6
GA      6
DE      6
CT      5
IA      5
OR      4
LA      4
NE      4
NM      3
KS      3
MN      2
ID      2
RI      1
SC      1
Name: count, dtype: int64

In [35]:
##job description length
df['desc_len'] = df['Job Description'].apply(lambda x : len(x))
df['desc_len']

0      2536
1      4783
2      3461
3      3883
4      2728
       ...
737    6162
738    6130
739    3078
740    1642
741    3673
Name: desc_len, Length: 742, dtype: int64

In [36]:
##Competitors
df['num_comp'] = df['Competitors'].apply(lambda x: len(x.split(',')) if x != '-1' else 0)

In [37]:
##hourl wage to annual
df['min_salary'] = df.apply(lambda x : x.min_salary*2 if x.hourly ==1 else x.min_salary , axis = 1)
df['max_salary'] = df.apply(lambda x : x.max_salary*2 if x.hourly ==1 else x.max_salary , axis = 1)

In [38]:
df[df.hourly == 1 ][['min_salary', 'max_salary', 'hourly']].head(20)

     min_salary  max_salary  hourly
165          34          48       1
177          42          68       1
197          36          50       1
202          42          68       1
210          30          50       1
246          34          48       1
271          42          68       1
337          36          50       1
345          48          78       1
357          42          68       1
363          50          56       1
408          42          58       1
409          20          34       1
492          36          50       1
509          48          78       1
533          42          68       1
542          50          56       1
617          42          58       1
618          20          34       1
645          54          94       1

In [42]:
df['Company_text'] = df['Company_text'].apply(lambda x : x.replace('\n', ''))
df['Company_text']

0                          Tecolote Research
1      University of Maryland Medical System
2                                    KnowBe4
3                                       PNNL
4                         Affinity Solutions
                       ...
737                                      GSK
738                               Eventbrite
739           Software Engineering Institute
740                             Numeric, LLC
741             Riverside Research Institute
Name: Company_text, Length: 742, dtype: str

In [43]:
df.describe()

,Rating,Founded,hourly,employer_provided,min_salary,max_salary,avg_salary,same_state,age,python_yn,R_yn,spark,aws,excel,desc_len,num_comp
count,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.0,742.000000,742.000000
mean,3.618868,1837.154987,0.032345,0.022911,74.719677,128.149596,100.626011,0.557951,53.119946,0.528302,0.002695,0.225067,0.237197,0.0,3869.545822,1.053908
std,0.801210,497.183763,0.177034,0.149721,30.980593,45.220324,38.855948,0.496965,54.223638,0.499535,0.051882,0.417908,0.425651,0.0,1521.495868,1.384239
min,-1.000000,-1.000000,0.000000,0.000000,15.000000,16.000000,13.500000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.0,407.000000,0.000000
25%,3.300000,1939.000000,0.000000,0.000000,52.000000,96.000000,73.500000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.0,2801.000000,0.000000
50%,3.700000,1988.000000,0.000000,0.000000,69.500000,124.000000,97.500000,1.000000,31.000000,1.000000,0.000000,0.000000,0.000000,0.0,3731.000000,0.000000
75%,4.000000,2007.000000,0.000000,0.000000,91.000000,155.000000,122.500000,1.000000,66.000000,1.000000,0.000000,0.000000,0.000000,0.0,4740.000000,3.000000
max,5.000000,2019.000000,1.000000,1.000000,202.000000,306.000000,254.000000,1.000000,283.000000,1.000000,1.000000,1.000000,1.000000,0.0,10051.000000,4.000000